let a = 2;
let b = "abc";
let c = "ab";
let d = true;
console.log(typeof(a));
console.log(typeof(b));
console.log(typeof(c));
console.log(typeof(d));
let e = String(a);
let f = Number(b);
console.log(e);
console.log(f);
let g = 10;
let h = 12;
let i = g + h;
console.log(++i);
console.log(i++);
console.log(i--);
console.log(--i);
let j = "dileep";
let k = "bothsa";
let l = j +" "+ k;
console.log(l);